-- ============================================================
-- Migration 166 : Copie les 3 scénarios DEMO → CERDIA Globale
--
-- Les scénarios originaux (Projet Démo 1, Projet Démo 2, Secret Garden H212)
-- existaient dans CERDIA Globale et ont été supprimés accidentellement.
-- Cette migration les recrée en copiant les données depuis le tenant DEMO,
-- avec de nouveaux UUIDs et status='draft' (converted_property_id nullé car
-- les propriétés converties appartiennent au tenant DEMO).
-- ============================================================

DO $$
DECLARE
  v_cerdia uuid := 'c0000000-0000-0000-0000-000000000001';
BEGIN

  INSERT INTO scenarios (
    id,
    organization_id,
    name,
    description,
    purchase_price,
    initial_fees,
    promoter_data,
    payment_terms,
    payment_type,
    down_payment,
    interest_rate,
    loan_duration,
    status,
    converted_property_id,
    converted_at,
    created_by,
    unit_number,
    address,
    country,
    state_region,
    promoter_name,
    broker_name,
    broker_email,
    company_name,
    transaction_fees,
    construction_status,
    delivery_date,
    completion_year,
    main_photo_url,
    owner_occupation_days,
    management_company_name,
    management_company_contact,
    management_company_email,
    deduct_initial_from_first_term,
    recurring_fees,
    purchase_currency,
    initial_fees_distribution,
    exchange_rate_at_creation,
    purchase_type,
    mortgage_rate_type,
    mortgage_term_years,
    mortgage_payment_frequency,
    mortgage_start_date,
    mortgage_renewal_date,
    mortgage_payment_amount
  ) VALUES

  -- Projet Démo 1
  (
    gen_random_uuid(),
    v_cerdia,
    'Projet Démo 1',
    NULL,
    167640.40,
    1883.60,
    '{"tax_rate":27,"rent_type":"nightly","monthly_rent":250,"rent_currency":"USD","occupancy_rate":65,"management_fees":35,"project_duration":10,"annual_appreciation":8,"annual_rent_increase":2}'::jsonb,
    '[{"label":"Paiement °1","due_date":"2025-04-20","percentage":20,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °2","due_date":"2025-10-20","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °3","due_date":"2026-04-20","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °4","due_date":"2026-10-20","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °5","due_date":"2027-03-01","percentage":50,"amount_type":"percentage","fixed_amount":0}]'::jsonb,
    'cash',
    0,
    0,
    25,
    'draft',
    NULL,
    NULL,
    NULL,
    '',
    '',
    '',
    '',
    'Promoteur Démo',
    'Courtier Démo',
    'courtier@demo.cerdia.ai',
    'Compagnie Démo Inc.',
    '{"type":"percentage","currency":"USD","percentage":0,"fixed_amount":0}'::jsonb,
    'in_progress',
    NULL,
    NULL,
    'https://svwolnvknfmakgmjhoml.supabase.co/storage/v1/object/public/scenario-documents/ba071f67-30b3-4c8c-be4e-32b40ca8c245/main-photo-1778787677313.png',
    60,
    NULL,
    NULL,
    NULL,
    false,
    '[]'::jsonb,
    'USD',
    'first_payment',
    1.35,
    'cash',
    'fixed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),

  -- Projet Démo 2
  (
    gen_random_uuid(),
    v_cerdia,
    'Projet Démo 2',
    NULL,
    236062.17,
    1883.60,
    '{"tax_rate":27,"rent_type":"nightly","monthly_rent":350,"rent_currency":"USD","occupancy_rate":65,"management_fees":35,"project_duration":10,"annual_appreciation":8,"annual_rent_increase":2}'::jsonb,
    '[{"label":"Paiement °1","due_date":"2025-05-05","percentage":20,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °2","due_date":"2025-11-30","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °3","due_date":"2026-05-30","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °4","due_date":"2027-11-30","percentage":10,"amount_type":"percentage","fixed_amount":0},{"label":"Paiement °5","due_date":"2027-03-01","percentage":50,"amount_type":"percentage","fixed_amount":0}]'::jsonb,
    'cash',
    0,
    0,
    25,
    'draft',
    NULL,
    NULL,
    NULL,
    '',
    '',
    '',
    '',
    'Promoteur Démo',
    'Courtier Démo',
    'courtier@demo.cerdia.ai',
    'Compagnie Démo Inc.',
    '{"type":"percentage","currency":"USD","percentage":0,"fixed_amount":0}'::jsonb,
    'in_progress',
    NULL,
    NULL,
    'https://svwolnvknfmakgmjhoml.supabase.co/storage/v1/object/public/scenario-documents/b06323b4-7670-4d9d-a3ed-0bd6f1ea2b1c/main-photo-1778787629399.png',
    60,
    NULL,
    NULL,
    NULL,
    false,
    '[]'::jsonb,
    'USD',
    'first_payment',
    1.35,
    'cash',
    'fixed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),

  -- Secret Garden H212
  (
    gen_random_uuid(),
    v_cerdia,
    'Secret Garden H212',
    NULL,
    211466.12,
    4709.00,
    '{"tax_rate":27,"rent_type":"nightly","monthly_rent":300,"rent_currency":"USD","occupancy_rate":65,"management_fees":35,"project_duration":10,"annual_appreciation":8,"annual_rent_increase":2}'::jsonb,
    '[{"label":"Paiement °1","due_date":"2025-09-15","percentage":0,"amount_type":"fixed_amount","fixed_amount":129720.4},{"label":"Paiement °2","due_date":"2025-10-30","percentage":0,"amount_type":"fixed_amount","fixed_amount":14968.93},{"label":"Paiement °3","due_date":"2025-11-30","percentage":0,"amount_type":"fixed_amount","fixed_amount":14968.93},{"label":"Paiement °4","due_date":"2026-01-30","percentage":0,"amount_type":"fixed_amount","fixed_amount":14968.94},{"label":"Paiement °5","due_date":"2026-03-15","percentage":0,"amount_type":"fixed_amount","fixed_amount":44907.2}]'::jsonb,
    'cash',
    0,
    0,
    25,
    'draft',
    NULL,
    NULL,
    NULL,
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '{"type":"percentage","currency":"USD","percentage":0,"fixed_amount":0}'::jsonb,
    'in_progress',
    NULL,
    NULL,
    '',
    60,
    NULL,
    NULL,
    NULL,
    false,
    '[]'::jsonb,
    'USD',
    'first_payment',
    1.35,
    'cash',
    'fixed',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

END $$;
