'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.projects': 'Projets',
    'nav.administration': 'Administration',
    'nav.logout': 'Déconnexion',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.totalInvestors': 'Total Investisseurs',
    'dashboard.realEstateInvestment': 'Investissement Immobilier',
    'dashboard.operationalExpenses': 'Dépenses Opération',
    'dashboard.currentAccount': 'Compte Courant',
    'dashboard.totalInvested': 'Total investi',
    'dashboard.currentValue': 'Valeur actuelle',
    'dashboard.totalROI': 'ROI total',
    'dashboard.activeProjects': 'Projets actifs',
    'dashboard.monthlyRevenue': 'Revenus mensuels',
    'dashboard.recentTransactions': 'Transactions récentes',
    'dashboard.viewAll': 'Voir tout',
    'dashboard.noTransactions': 'Aucune transaction récente',
    'dashboard.cadContributions': 'Apports CAD',
    'dashboard.investors': 'investisseurs',
    'dashboard.investor': 'investisseur',
    'dashboard.properties': 'propriétés',
    'dashboard.property': 'propriété',
    'dashboard.realEstatePortfolio': 'Portefeuille Immobilier',
    'dashboard.investorBreakdown': 'Répartition des Investisseurs',
    'dashboard.upcomingPayments': 'Paiements à venir',
    'dashboard.payment': 'paiement',
    'dashboard.payments': 'paiements',
    'dashboard.pending': 'en attente',
    'dashboard.noProperties': 'Aucune propriété pour le moment',
    'dashboard.noInvestors': 'Aucun investisseur pour le moment',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.availableFunds': 'Fonds disponibles CAD',
    'dashboard.capexRnD': 'CAPEX, R&D, etc. (CAD)',
    'dashboard.progress': 'Progression',
    'dashboard.paid': 'payé',
    'dashboard.remaining': 'restant',
    'dashboard.expectedROI': 'ROI attendu',
    'dashboard.totalPaidCAD': 'Total payé en CAD',
    'dashboard.actualCostCAD': 'Coût réel en économie canadienne',
    'dashboard.ownership': 'du portefeuille',
    'dashboard.shares': 'parts',
    'dashboard.reservedOn': 'Réservé le',
    'dashboard.exchangeRate': 'Taux de change USD→CAD',
    'dashboard.updatedDaily': 'mis à jour quotidiennement',
    'dashboard.overdue': 'En retard',
    'dashboard.urgent': 'Urgent',
    'dashboard.soon': 'Bientôt',
    'dashboard.upcoming': 'À venir',
    'dashboard.daysLate': 'jour(s) de retard',
    'dashboard.today': 'Aujourd\'hui',
    'dashboard.inDays': 'Dans',
    'dashboard.days': 'jour(s)',
    'dashboard.dueDate': 'Échéance',
    'dashboard.contract': 'Contrat',
    'dashboard.estimated': 'Estimé',
    'dashboard.paidAmount': 'Payé',
    'dashboard.rate': 'Taux',
    'dashboard.currentRate': 'Taux actuel',

    // Projects
    'projects.title': 'Gestion des Projets',
    'projects.subtitle': 'Gérez vos propriétés immobilières',
    'projects.add': 'Ajouter un projet',
    'projects.cancel': 'Annuler',
    'projects.new': 'Nouveau projet',
    'projects.edit': 'Modifier le projet',
    'projects.name': 'Nom du projet',
    'projects.location': 'Localisation',
    'projects.status': 'Statut',
    'projects.totalCost': 'Coût total',
    'projects.paidAmount': 'Montant payé',
    'projects.reservationDate': 'Date de réservation',
    'projects.expectedROI': 'ROI attendu',
    'projects.currency': 'Devise',
    'projects.paymentScheduleType': 'Type de paiement',
    'projects.reservationDeposit': 'Acompte de réservation',
    'projects.save': 'Enregistrer',
    'projects.delete': 'Supprimer',
    'projects.confirmDelete': 'Êtes-vous sûr de vouloir supprimer ce projet',
    'projects.noProjects': 'Aucun projet',
    'projects.addFirst': 'Commencez par ajouter votre premier projet',
    'projects.duration': 'Durée',
    'projects.cannotAddManually': 'Impossible d\'ajouter de nouvelles propriétés. Utilisez l\'onglet Évaluateur pour créer un scénario.',
    'projects.convertedFromScenarios': 'Projets convertis depuis les scénarios approuvés',
    'projects.updateError': 'Erreur lors de la modification: ',

    // Administration
    'admin.title': 'Administration',
    'admin.investors': 'Investisseurs',
    'admin.transactions': 'Transactions',
    'admin.currentAccount': 'Compte Courant 2025',
    'admin.capex': 'CAPEX 2025',
    'admin.rd': 'R&D / Dividendes',

    // Investors
    'investors.title': 'Gestion des Investisseurs',
    'investors.subtitle': 'Gérez les investisseurs et leurs documents',
    'investors.add': 'Ajouter un investisseur',
    'investors.new': 'Nouvel investisseur',
    'investors.edit': 'Modifier l\'investisseur',
    'investors.firstName': 'Prénom',
    'investors.lastName': 'Nom',
    'investors.email': 'Email',
    'investors.phone': 'Téléphone',
    'investors.username': 'Nom d\'utilisateur',
    'investors.shareClass': 'Classe de parts',
    'investors.totalShares': 'Total parts',
    'investors.shareValue': 'Valeur par part',
    'investors.totalInvested': 'Total investi',
    'investors.percentOwnership': '% de propriété',
    'investors.investmentType': 'Type d\'investissement',
    'investors.joinDate': 'Date d\'adhésion',
    'investors.accessLevel': 'Niveau d\'accès',
    'investors.permissions': 'Permissions',
    'investors.documents': 'Documents',
    'investors.currentValue': 'Valeur actuelle',
    'investors.shares': 'Parts',
    'investors.ownership': 'Propriété',
    'investors.memberSince': 'Membre depuis',
    'investors.noInvestors': 'Aucun investisseur',
    'investors.addFirstInvestor': 'Commencez par ajouter votre premier investisseur',

    // Transactions
    'transactions.title': 'Transactions',
    'transactions.new': 'Nouvelle transaction',
    'transactions.edit': 'Modifier la transaction',
    'transactions.date': 'Date',
    'transactions.type': 'Type',
    'transactions.amount': 'Montant',
    'transactions.description': 'Description',
    'transactions.category': 'Catégorie',
    'transactions.paymentMethod': 'Méthode de paiement',
    'transactions.referenceNumber': 'Numéro de référence',
    'transactions.status': 'Statut',
    'transactions.investor': 'Investisseur',
    'transactions.property': 'Propriété',
    'transactions.none': 'Aucune',
    'transactions.noTransactions': 'Aucune transaction',
    'transactions.addFirst': 'Commencez par ajouter votre première transaction',
    'transactions.totalIn': 'Entrées',
    'transactions.totalOut': 'Sorties',
    'transactions.balance': 'Solde',
    'transactions.filter': 'Filtrer',
    'transactions.allTypes': 'Tous les types',
    'transactions.allCategories': 'Toutes les catégories',
    'transactions.noMatch': 'Aucune transaction ne correspond aux filtres sélectionnés',

    // Transaction Types
    'transactionType.investment': 'Investissement',
    'transactionType.payment': 'Paiement',
    'transactionType.dividend': 'Dividende',
    'transactionType.expense': 'Dépense',

    // Categories
    'category.capital': 'Capital',
    'category.operation': 'Opération',
    'category.maintenance': 'Maintenance',
    'category.admin': 'Administration',

    // Status
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.suspended': 'Suspendu',
    'status.complete': 'Complété',
    'status.pending': 'En attente',
    'status.cancelled': 'Annulé',
    'status.reservation': 'Réservation',
    'status.construction': 'Construction',
    'status.completed': 'Complété',
    'status.rented': 'Loué',

    // Payment Methods
    'paymentMethod.transfer': 'Virement',
    'paymentMethod.check': 'Chèque',
    'paymentMethod.cash': 'Espèces',
    'paymentMethod.card': 'Carte',

    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.loading': 'Chargement...',
    'common.saving': 'Enregistrement...',
    'common.actions': 'Actions',
    'common.download': 'Télécharger',
    'common.upload': 'Télécharger',
    'common.viewDetails': 'Voir les détails',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.years': 'ans',

    // Documents
    'documents.title': 'Documents',
    'documents.upload': 'Cliquez pour télécharger un document',
    'documents.uploading': 'Téléchargement en cours...',
    'documents.noDocuments': 'Aucun document pour cet investisseur',
    'documents.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce document ?',

    // Current Account
    'currentAccount.title': 'Compte Courant',
    'currentAccount.subtitle': 'Vue agrégée des transactions par catégorie',
    'currentAccount.totalRevenues': 'Total Revenus',
    'currentAccount.operationalCosts': 'Coûts Opération',
    'currentAccount.projectExpenses': 'Dépenses Projet',
    'currentAccount.netIncome': 'Revenu Net',
    'currentAccount.revenueDetails': 'Détails Revenus',
    'currentAccount.operationDetails': 'Détails Coûts Opération',
    'currentAccount.projectDetails': 'Détails Dépenses Projet',
    'currentAccount.rentalIncome': 'Revenus locatifs',
    'currentAccount.otherIncome': 'Autres revenus',
    'currentAccount.managementFees': 'Frais gestion',
    'currentAccount.utilities': 'Services publics',
    'currentAccount.insurance': 'Assurances',
    'currentAccount.maintenance': 'Maintenance',
    'currentAccount.propertyTaxes': 'Taxes foncières',
    'currentAccount.renovations': 'Rénovations',
    'currentAccount.furnishing': 'Ameublement',
    'currentAccount.otherProjects': 'Autres projets',
    'currentAccount.byProject': 'Détails par Projet',
    'currentAccount.noData': 'Aucune donnée',
    'currentAccount.noTransactionsFor': 'Aucune transaction pour',

    // Months
    'month.january': 'Janvier',
    'month.february': 'Février',
    'month.march': 'Mars',
    'month.april': 'Avril',
    'month.may': 'Mai',
    'month.june': 'Juin',
    'month.july': 'Juillet',
    'month.august': 'Août',
    'month.september': 'Septembre',
    'month.october': 'Octobre',
    'month.november': 'Novembre',
    'month.december': 'Décembre',

    // Investment Types
    'investmentType.capital': 'Capital',
    'investmentType.debt': 'Dette',
    'investmentType.mixed': 'Mixte',

    // Access Levels
    'accessLevel.investor': 'Investisseur',
    'accessLevel.admin': 'Administrateur',

    // Errors & Messages
    'error.generic': 'Une erreur est survenue',
    'error.loadingFailed': 'Échec du chargement des données',
    'error.saveFailed': 'Échec de l\'enregistrement',
    'error.deleteFailed': 'Échec de la suppression',
    'success.saved': 'Enregistré avec succès',
    'success.deleted': 'Supprimé avec succès',
    'success.uploaded': 'Téléchargé avec succès',

    // Tax Reports
    'taxReports.title': 'Rapports Fiscaux',
    'taxReports.subtitle': 'T1135 et T2209 pour déclaration fiscale canadienne',
    'taxReports.foreignAssets': 'Biens étrangers',
    'taxReports.foreignTaxCredits': 'Crédits d\'impôt étrangers',
    'taxReports.t1135Required': 'T1135 requis : Vos actifs étrangers dépassent 100 000$ CAD',
    'taxReports.totalForeignAssets': 'Total biens étrangers',
    'taxReports.foreignIncome': 'Revenus étrangers',
    'taxReports.foreignProperties': 'Propriétés étrangères',
    'taxReports.foreignPropertiesDetail': 'Détail des propriétés étrangères',
    'taxReports.exportPDF': 'Exporter PDF',
    'taxReports.country': 'Pays',
    'taxReports.originalCost': 'Coût original',
    'taxReports.costCAD': 'Coût (CAD)',
    'taxReports.noForeignAssets': 'Aucun bien étranger pour cette année',
    'taxReports.totalForeignIncome': 'Total revenus étrangers',
    'taxReports.totalForeignTaxPaid': 'Total impôts étrangers payés',
    'taxReports.totalTaxCredit': 'Total crédits d\'impôt',
    'taxReports.byCountry': 'Par pays',
    'taxReports.taxPaid': 'Impôt payé',
    'taxReports.taxCredit': 'Crédit d\'impôt',
    'taxReports.noForeignTaxData': 'Aucune donnée fiscale étrangère pour cette année',

    // Transaction Attachments
    'attachments.title': 'Pièces Jointes',
    'attachments.close': 'Fermer',
    'attachments.uploading': 'Téléchargement en cours...',
    'attachments.dragDrop': 'Glissez des fichiers ici ou cliquez pour sélectionner',
    'attachments.supportedFormats': 'PDF, Images, Word, Excel (max 10 MB par fichier)',
    'attachments.loading': 'Chargement...',
    'attachments.noAttachments': 'Aucune pièce jointe pour cette transaction',
    'attachments.createTransactionFirst': 'Veuillez d\'abord créer la transaction avant d\'ajouter des pièces jointes.',
    'attachments.downloadFile': 'Télécharger',
    'attachments.deleteFile': 'Supprimer',
    'attachments.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer',
    'attachments.uploadSuccess': 'Fichier(s) téléchargé(s) avec succès!',
    'attachments.uploadError': 'Erreur lors du téléchargement',
    'attachments.deleteSuccess': 'Fichier supprimé avec succès!',
    'attachments.deleteError': 'Erreur lors de la suppression',
    'attachments.downloadError': 'Erreur lors du téléchargement',

    // Scenarios / Evaluator
    'scenarios.title': 'Scénarios d\'Évaluation',
    'scenarios.subtitle': 'Créer, analyser et voter sur les opportunités d\'investissement',
    'scenarios.newScenario': 'Nouveau scénario',
    'scenarios.noScenarios': 'Aucun scénario',
    'scenarios.createFirst': 'Créez votre premier scénario d\'évaluation',
    'scenarios.name': 'Nom du projet',
    'scenarios.unitNumber': 'Numéro d\'unité (Condo ou Appartement)',
    'scenarios.address': 'Adresse (optionnel)',
    'scenarios.country': 'Pays',
    'scenarios.stateRegion': 'État/Région/Province',
    'scenarios.promoterName': 'Nom du promoteur',
    'scenarios.brokerName': 'Nom du courtier',
    'scenarios.brokerEmail': 'Courriel du courtier',
    'scenarios.companyName': 'Nom de compagnie',
    'scenarios.purchasePrice': 'Prix d\'achat ($)',
    'scenarios.initialFees': 'Frais initiaux ($)',
    'scenarios.transactionFeesType': 'Frais de transaction',
    'scenarios.amountValue': 'Montant',
    'scenarios.currency': 'Devise',
    'scenarios.rentAmount': 'Montant du loyer',
    'scenarios.rentType': 'Type de loyer',
    'scenarios.rentCurrency': 'Devise du loyer',
    'scenarios.monthly': 'Mensuel',
    'scenarios.nightly': 'Par nuit',
    'scenarios.constructionStatus': 'Statut de Construction',
    'scenarios.constructionStatusLabel': 'Statut',
    'scenarios.inProgress': 'En construction',
    'scenarios.completed': 'Construction terminée',
    'scenarios.deliveryDate': 'Date de livraison',
    'scenarios.completionYear': 'Année de fin',
    'scenarios.monthlyRent': 'Loyer mensuel ($)',
    'scenarios.annualAppreciation': 'Appréciation annuelle (%)',
    'scenarios.occupancyRate': 'Taux d\'occupation (%)',
    'scenarios.managementFees': 'Frais de gestion (%)',
    'scenarios.projectDuration': 'Durée du projet (années)',
    'scenarios.taxRate': 'Taux d\'imposition sur revenus locatifs (%)',
    'scenarios.annualRentIncrease': 'Augmentation locative annuelle (%)',
    'scenarios.rentalIncomeAnalysis': 'Analyse des Revenus Locatifs',
    'scenarios.numberOfNights': 'Nombre de nuits',
    'scenarios.accommodationPrice': 'Prix d\'hébergement',
    'scenarios.annualIncome': 'Rendement annuel',
    'scenarios.annualRevenue': 'Revenu annuel',
    'scenarios.tax': 'Impôt',
    'scenarios.netIncome': 'Revenu net',
    'scenarios.netIncomeComparison': 'Comparaison des revenus nets',
    'scenarios.roiTimeline': 'Chronologie du ROI avec augmentation locative',
    'scenarios.nightlyRate': 'Tarif de nuit',
    'scenarios.cumulativeIncome': 'Revenu cumulatif',
    'scenarios.roiProgress': 'Progression du ROI',
    'scenarios.paymentTerms': 'Termes de Paiement',
    'scenarios.addTerm': 'Ajouter un terme',
    'scenarios.noPaymentTerms': 'Aucun terme de paiement défini',
    'scenarios.termLabel': 'Libellé',
    'scenarios.termLabelPlaceholder': 'Ex: Acompte initial',
    'scenarios.amountType': 'Type de montant',
    'scenarios.percentage': 'Pourcentage (%)',
    'scenarios.fixedAmount': 'Montant fixe',
    'scenarios.percentageValue': 'Pourcentage (%)',
    'scenarios.amountUSD': 'Montant (USD)',
    'scenarios.dueDate': 'Date d\'échéance',
    'scenarios.calculatedAmount': 'Montant calculé',
    'scenarios.basicInfo': 'Informations de base',
    'scenarios.promoterData': 'Données du promoteur',
    'scenarios.promoterDocuments': 'Documents du promoteur',
    'scenarios.analyze': 'Analyser',
    'scenarios.analyzing': 'Analyse en cours...',
    'scenarios.submitForVote': 'Soumettre au vote',
    'scenarios.forceApproval': 'Forcer l\'approbation (Admin)',
    'scenarios.markAsPurchased': 'Marquer comme acheté',
    'scenarios.exportPDF': 'Exporter PDF',
    'scenarios.back': 'Retour',
    'scenarios.create': 'Créer le scénario',
    'scenarios.view': 'Voir',
    'scenarios.required': 'requis',
    'scenarios.optional': 'optionnel',
    'scenarios.toBeDefinedLocation': 'À définir',

    // Scenario Status
    'scenarioStatus.draft': 'Brouillon',
    'scenarioStatus.pending_vote': 'En vote',
    'scenarioStatus.approved': 'Approuvé',
    'scenarioStatus.rejected': 'Rejeté',
    'scenarioStatus.purchased': 'Acheté',

    // Scenario Types
    'scenarioType.conservative': 'Conservateur',
    'scenarioType.moderate': 'Modéré',
    'scenarioType.optimistic': 'Élevé',

    // Scenario Results
    'scenarioResults.avgAnnualReturn': 'Rendement annuel moyen',
    'scenarioResults.totalReturn': 'Retour total',
    'scenarioResults.finalValue': 'Valeur finale',
    'scenarioResults.breakEven': 'Point mort',
    'scenarioResults.year': 'Année',
    'scenarioResults.evaluation': 'Évaluation',
    'scenarioResults.projection': 'Projection annuelle',
    'scenarioResults.propertyValue': 'Valeur bien',
    'scenarioResults.revenues': 'Revenus',
    'scenarioResults.fees': 'Frais',
    'scenarioResults.net': 'Net',
    'scenarioResults.cashflow': 'Cashflow',
    'scenarioResults.recommendation': 'Recommandation',
    'scenarioResults.recommended': 'recommandé',
    'scenarioResults.notRecommended': 'déconseillé',
    'scenarioResults.toConsider': 'à considérer avec prudence',
    'scenarioResults.scenarioLabel': 'Scénario',
    'scenarioResults.project': 'Projet',
    'scenarioResults.over': 'sur',
    'scenarioResults.attractiveReturn': 'Rendement attractif',
    'scenarioResults.lowReturn': 'Rendement faible',
    'scenarioResults.moderateReturn': 'Rendement modéré',
    'scenarioResults.quickBreakEven': 'Point mort rapide',
    'scenarioResults.distantBreakEven': 'Point mort éloigné',
    'scenarioResults.acceptableBreakEven': 'Point mort acceptable',

    // Voting
    'voting.status': 'Statut du vote',
    'voting.votes': 'votes',
    'voting.votesReceived': 'Votes reçus',
    'voting.approvals': 'Approbations',
    'voting.rejections': 'Rejets',
    'voting.approvalRate': 'Taux d\'approbation',
    'voting.yourVote': 'Votre vote',
    'voting.approve': 'Approuver',
    'voting.reject': 'Rejeter',
    'voting.voteRecorded': 'Vote enregistré!',
    'voting.voteError': 'Erreur lors de l\'enregistrement du vote',
    'voting.individualVotes': 'Votes individuels',
    'voting.noVotingPermission': 'Vous n\'avez pas la permission de voter sur ce scénario',
    'voting.onlyAdminsCanForce': 'Seuls les administrateurs peuvent forcer l\'approbation',
    'voting.forceConfirm': 'Êtes-vous sûr de vouloir FORCER l\'approbation de ce scénario?\n\nCeci contourne le système de vote normal et marque le scénario comme approuvé par les investisseurs.',
    'voting.forcedSuccess': 'Scénario marqué comme approuvé (forcé par admin)',
    'voting.forceError': 'Erreur lors du forçage de l\'approbation',
    'voting.totalEligibleVoters': 'Votants éligibles',

    // Documents
    'scenarioDocuments.title': 'Documents du promoteur',
    'scenarioDocuments.upload': 'Ajouter',
    'scenarioDocuments.uploading': 'Upload...',
    'scenarioDocuments.noDocuments': 'Aucun document',
    'scenarioDocuments.view': 'Voir',
    'scenarioDocuments.delete': 'Supprimer',
    'scenarioDocuments.uploadSuccess': 'Document uploadé avec succès!',
    'scenarioDocuments.uploadError': 'Erreur lors de l\'upload du document',
    'scenarioDocuments.deleteConfirm': 'Voulez-vous vraiment supprimer ce document?',
    'scenarioDocuments.deleteSuccess': 'Document supprimé',
    'scenarioDocuments.deleteError': 'Erreur lors de la suppression',
    'scenarioDocuments.fileTooLarge': 'Le fichier est trop volumineux (max 50MB)',

    // Scenario Conversion
    'scenarioConvert.mustBeApproved': 'Le scénario doit être approuvé avant de le marquer comme acheté',
    'scenarioConvert.confirmConversion': 'Voulez-vous convertir ce scénario en projet actif?',
    'scenarioConvert.success': 'Scénario converti en projet actif avec succès!',
    'scenarioConvert.error': 'Erreur lors de la conversion en projet',
    'scenarioConvert.analyzeFirst': 'Veuillez d\'abord analyser le scénario avant de le soumettre au vote',
    'scenarioConvert.votingInfo': 'Soumis au vote des investisseurs',
    'scenarioConvert.approvedInfo': 'Approuvé - Prêt à être acheté',
    'scenarioConvert.purchasedInfo': 'Converti en projet actif',

    // Project Scenario Info
    'projectScenario.title': 'Scénario d\'évaluation',
    'projectScenario.createdOn': 'Créé le',
    'projectScenario.from': 'Issu du scénario',

    // Admin - Investor Voting Rights
    'investors.votingRights': 'Droit de vote',
    'investors.canVote': 'Peut voter sur les scénarios',

    // Messages
    'scenarios.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'scenarios.created': 'Scénario créé avec succès!',
    'scenarios.createError': 'Erreur lors de la création du scénario',
    'scenarios.analyzed': 'Analyse terminée! Les 3 scénarios ont été générés.',
    'scenarios.analyzeError': 'Erreur lors de l\'analyse du scénario',
    'scenarios.submitted': 'Scénario soumis au vote des investisseurs!',
    'scenarios.submitError': 'Erreur lors de la soumission au vote',
    'scenarios.noAddProjects': 'Impossible d\'ajouter de nouvelles propriétés. Utilisez l\'onglet Évaluateur pour créer un scénario.',

    // Project List Messages
    'projects.convertedFrom': 'Projets convertis depuis les scénarios approuvés',
    'projects.noActiveProjects': 'Aucun projet actif',
    'projects.createdViaEvaluator': 'Les projets sont créés automatiquement depuis l\'onglet',
    'projects.workflow': 'Créez un scénario → Analysez → Vote des investisseurs → Marquez comme acheté',

    // User Guide
    'userGuide.title': 'Mode d\'emploi',
    'userGuide.subtitle': 'Guide complet d\'utilisation de la plateforme CERDIA',
    'userGuide.searchPlaceholder': 'Rechercher dans le guide...',
    'userGuide.noResults': 'Aucun résultat trouvé pour',
    'userGuide.dashboard': 'Tableau de bord',
    'userGuide.projectManagement': 'Gestion de Projets',
    'userGuide.evaluator': 'Évaluateur / Scénarios',
    'userGuide.reservations': 'Calendrier de Réservations',
    'userGuide.administration': 'Administration',
    'userGuide.treasury': 'Trésorerie',
    'userGuide.projectManagementAdmin': 'Gestion de Projet (Admin)',
    'userGuide.budgeting': 'Budgétisation',
    'userGuide.userManual': 'Mode d\'emploi',
    'userGuide.notepad': 'Bloc-notes',

    // User Guide - Dashboard
    'userGuide.dashboardOverview': 'Vue d\'ensemble',
    'userGuide.dashboardOverviewDesc': 'Le tableau de bord affiche un résumé de vos investissements en temps réel.',
    'userGuide.dashboardStep1': 'Total Investisseurs: Somme des apports en CAD',
    'userGuide.dashboardStep2': 'Investissement Immobilier: Montant investi en USD converti en CAD',
    'userGuide.dashboardStep3': 'Dépenses Opération: CAPEX + R&D',
    'userGuide.dashboardStep4': 'Compte Courant: Fonds disponibles calculés automatiquement',
    'userGuide.exchangeRate': 'Taux de change',
    'userGuide.exchangeRateDesc': 'Le widget affiche le taux USD→CAD mis à jour quotidiennement depuis la Banque du Canada.',
    'userGuide.properties': 'Propriétés',
    'userGuide.propertiesDesc': 'Liste de vos propriétés avec progression des paiements et ROI attendu.',

    // User Guide - Project Management
    'userGuide.projectOverview': 'Vue d\'ensemble',
    'userGuide.projectOverviewDesc': 'Gère vos projets immobiliers avec suivi des échéances et milestones.',
    'userGuide.createProject': 'Créer un projet',
    'userGuide.createProjectDesc': 'Créez un nouveau projet en cliquant sur "Nouveau Projet".',
    'userGuide.createProjectStep1': 'Entrez le nom du projet',
    'userGuide.createProjectStep2': 'Définissez les dates de début et fin',
    'userGuide.createProjectStep3': 'Ajoutez une description',
    'userGuide.createProjectStep4': 'Sélectionnez le statut initial',
    'userGuide.milestones': 'Jalons (Milestones)',
    'userGuide.milestonesDesc': 'Définissez les étapes clés du projet avec dates et livrables.',
    'userGuide.risks': 'Risques',
    'userGuide.risksDesc': 'Identifiez et gérez les risques potentiels du projet.',
    'userGuide.contractors': 'Entrepreneurs',
    'userGuide.contractorsDesc': 'Gérez les contacts et contrats des entrepreneurs impliqués.',

    // User Guide - Evaluator
    'userGuide.scenarioCreation': 'Création de scénarios',
    'userGuide.scenarioCreationDesc': 'Créez des scénarios d\'investissement pour évaluer la rentabilité.',
    'userGuide.scenarioStep1': 'Cliquez sur "Nouveau Scénario"',
    'userGuide.scenarioStep2': 'Entrez les informations de la propriété',
    'userGuide.scenarioStep3': 'Définissez le prix d\'achat et frais',
    'userGuide.scenarioStep4': 'Configurez les données promoteur (loyer, charges, etc.)',
    'userGuide.scenarioStep5': 'Ajoutez les termes de paiement',
    'userGuide.scenarioTypes': 'Types de scénarios',
    'userGuide.scenarioTypesDesc': 'Trois types disponibles: Conservateur, Modéré, Optimiste avec projections financières différentes.',
    'userGuide.documents': 'Documents',
    'userGuide.documentsDesc': 'Téléchargez et gérez les documents liés au scénario (contrats, plans, etc.).',
    'userGuide.vote': 'Vote',
    'userGuide.voteDesc': 'Soumettez le scénario au vote des investisseurs pour validation.',
    'userGuide.reservationsAfterPurchase': 'Réservations (après achat)',
    'userGuide.reservationsAfterPurchaseDesc': 'Gérez le calendrier de réservation et les revenus locatifs une fois la propriété achetée.',

    // User Guide - Reservations
    'userGuide.calendarView': 'Vue du calendrier',
    'userGuide.calendarViewDesc': 'Visualisez toutes les réservations pour vos propriétés louées.',
    'userGuide.createReservation': 'Créer une réservation',
    'userGuide.createReservationDesc': 'Ajoutez une nouvelle réservation en sélectionnant les dates et la propriété.',
    'userGuide.management': 'Gestion',
    'userGuide.managementDesc': 'Modifiez ou annulez des réservations existantes.',

    // User Guide - Administration
    'userGuide.investors': 'Investisseurs',
    'userGuide.investorsDesc': 'Gérez les investisseurs, leurs parts et permissions.',
    'userGuide.investorsStep1': 'Ajouter un investisseur: Entrez nom, email, actions',
    'userGuide.investorsStep2': 'Modifier: Cliquez sur l\'icône crayon',
    'userGuide.investorsStep3': 'Supprimer: Icône poubelle (avec confirmation)',
    'userGuide.transactions': 'Transactions',
    'userGuide.transactionsDesc': 'Enregistrez toutes les transactions financières.',
    'userGuide.transactionsStep1': 'Types: Investissement, Paiement, Dividende, Autre',
    'userGuide.transactionsStep2': 'Attachez des justificatifs (factures, reçus)',
    'userGuide.transactionsStep3': 'Liez aux investisseurs et propriétés',
    'userGuide.capex': 'CAPEX',
    'userGuide.capexDesc': 'Gérez les dépenses en capital (investissement et opération).',
    'userGuide.rdDividends': 'R&D / Dividendes',
    'userGuide.rdDividendsDesc': 'Suivez les dépenses R&D et distributions de dividendes.',
    'userGuide.taxReports': 'Rapports Fiscaux',
    'userGuide.taxReportsDesc': 'Générez des rapports fiscaux pour les autorités.',
    'userGuide.roiPerformance': 'Performance ROI',
    'userGuide.roiPerformanceDesc': 'Analysez le retour sur investissement par propriété et global.',
    'userGuide.syncRevenue': 'Sync Revenus',
    'userGuide.syncRevenueDesc': 'Synchronisez les revenus depuis les plateformes de réservation (Booking.com, Airbnb).',

    // User Guide - Treasury
    'userGuide.treasuryOverview': 'Vue d\'ensemble',
    'userGuide.treasuryOverviewDesc': 'Tableau de bord financier avec solde actuel, entrées/sorties du mois.',
    'userGuide.cashFlowForecasts': 'Prévisions de flux',
    'userGuide.cashFlowForecastsDesc': 'Visualisez les flux de trésorerie prévisionnels sur 12 mois.',
    'userGuide.bankReconciliation': 'Rapprochement bancaire',
    'userGuide.bankReconciliationDesc': 'Rapprochez vos transactions avec vos relevés bancaires.',
    'userGuide.paymentSchedule': 'Calendrier de paiements',
    'userGuide.paymentScheduleDesc': 'Gérez les paiements programmés avec alertes d\'échéance.',
    'userGuide.alerts': 'Alertes',
    'userGuide.alertsDesc': 'Configurez des alertes pour solde faible, paiements en retard, etc.',

    // User Guide - Project Management Admin
    'userGuide.adminAccess': 'Accès administrateur',
    'userGuide.adminAccessDesc': 'Version administrative avec fonctionnalités avancées de gestion de projet.',
    'userGuide.timeline': 'Timeline',
    'userGuide.timelineDesc': 'Vue chronologique des projets avec dépendances.',
    'userGuide.resources': 'Ressources',
    'userGuide.resourcesDesc': 'Allocation des ressources (budget, personnel, matériel).',

    // User Guide - Budgeting
    'userGuide.budgetCreation': 'Création de budgets',
    'userGuide.budgetCreationDesc': 'Créez des budgets annuels par catégorie.',
    'userGuide.budgetStep1': 'Sélectionnez l\'année fiscale',
    'userGuide.budgetStep2': 'Ajoutez des lignes budgétaires (nom, catégorie, montant)',
    'userGuide.budgetStep3': 'Définissez les périodes (mensuel, trimestriel, annuel)',
    'userGuide.budgetStep4': 'Configurez les seuils d\'alerte',
    'userGuide.consumptionTracking': 'Suivi de consommation',
    'userGuide.consumptionTrackingDesc': 'Visualisez le % de budget consommé avec indicateurs visuels (vert/orange/rouge).',
    'userGuide.varianceAnalysis': 'Analyse d\'écart',
    'userGuide.varianceAnalysisDesc': 'Comparez prévu vs réalisé pour identifier les dépassements.',
    'userGuide.approval': 'Approbation',
    'userGuide.approvalDesc': 'Workflow d\'approbation pour les modifications de budget.',

    // User Guide - Notepad
    'userGuide.interactiveGuide': 'Guide interactif',
    'userGuide.interactiveGuideDesc': 'Ce guide que vous consultez actuellement!',
    'userGuide.todoLists': 'To-Do Lists',
    'userGuide.todoListsDesc': 'Créez et gérez vos listes de tâches personnelles.',
    'userGuide.todoStep1': 'Créez une nouvelle liste',
    'userGuide.todoStep2': 'Ajoutez des tâches',
    'userGuide.todoStep3': 'Cochez les tâches complétées',
    'userGuide.todoStep4': 'Supprimez les tâches obsolètes',
    'userGuide.notes': 'Notes',
    'userGuide.notesDesc': 'Prenez des notes libres liées à vos projets.',

    // Notes Manager
    'notes.title': 'Bloc-notes',
    'notes.todoLists': 'To-Do Lists',
    'notes.notes': 'Notes',
    'notes.newList': 'Nouvelle liste',
    'notes.newNote': 'Nouvelle note',
    'notes.listName': 'Nom de la liste',
    'notes.listNamePlaceholder': 'Ma liste de tâches',
    'notes.createList': 'Créer',
    'notes.cancel': 'Annuler',
    'notes.addTask': 'Ajouter une tâche',
    'notes.taskPlaceholder': 'Que faut-il faire?',
    'notes.add': 'Ajouter',
    'notes.deleteList': 'Supprimer la liste',
    'notes.confirmDeleteList': 'Êtes-vous sûr de vouloir supprimer cette liste et toutes ses tâches?',
    'notes.noLists': 'Aucune to-do list',
    'notes.createFirstList': 'Créez votre première to-do list pour vous organiser',
    'notes.tasksCompleted': 'tâches complétées',
    'notes.noteTitle': 'Titre de la note',
    'notes.noteTitlePlaceholder': 'Ma note',
    'notes.noteContent': 'Contenu',
    'notes.noteContentPlaceholder': 'Écrivez votre note ici...',
    'notes.save': 'Enregistrer',
    'notes.delete': 'Supprimer',
    'notes.confirmDeleteNote': 'Êtes-vous sûr de vouloir supprimer cette note?',
    'notes.noNotes': 'Aucune note',
    'notes.createFirstNote': 'Créez votre première note pour garder vos idées',
    'notes.createdOn': 'Créée le',
    'notes.updatedOn': 'Modifiée le',
    'notes.edit': 'Modifier',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Projects',
    'nav.administration': 'Administration',
    'nav.logout': 'Logout',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.totalInvestors': 'Total Investors',
    'dashboard.realEstateInvestment': 'Real Estate Investment',
    'dashboard.operationalExpenses': 'Operational Expenses',
    'dashboard.currentAccount': 'Current Account',
    'dashboard.totalInvested': 'Total Invested',
    'dashboard.currentValue': 'Current Value',
    'dashboard.totalROI': 'Total ROI',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.viewAll': 'View All',
    'dashboard.noTransactions': 'No recent transactions',
    'dashboard.cadContributions': 'CAD Contributions',
    'dashboard.investors': 'investors',
    'dashboard.investor': 'investor',
    'dashboard.properties': 'properties',
    'dashboard.property': 'property',
    'dashboard.realEstatePortfolio': 'Real Estate Portfolio',
    'dashboard.investorBreakdown': 'Investor Breakdown',
    'dashboard.upcomingPayments': 'Upcoming Payments',
    'dashboard.payment': 'payment',
    'dashboard.payments': 'payments',
    'dashboard.pending': 'pending',
    'dashboard.noProperties': 'No properties yet',
    'dashboard.noInvestors': 'No investors yet',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.availableFunds': 'Available Funds CAD',
    'dashboard.capexRnD': 'CAPEX, R&D, etc. (CAD)',
    'dashboard.progress': 'Progress',
    'dashboard.paid': 'paid',
    'dashboard.remaining': 'remaining',
    'dashboard.expectedROI': 'Expected ROI',
    'dashboard.totalPaidCAD': 'Total Paid in CAD',
    'dashboard.actualCostCAD': 'Actual cost in Canadian economy',
    'dashboard.ownership': 'of portfolio',
    'dashboard.shares': 'shares',
    'dashboard.reservedOn': 'Reserved on',
    'dashboard.exchangeRate': 'USD→CAD Exchange Rate',
    'dashboard.updatedDaily': 'updated daily',
    'dashboard.overdue': 'Overdue',
    'dashboard.urgent': 'Urgent',
    'dashboard.soon': 'Soon',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.daysLate': 'day(s) late',
    'dashboard.today': 'Today',
    'dashboard.inDays': 'In',
    'dashboard.days': 'day(s)',
    'dashboard.dueDate': 'Due date',
    'dashboard.contract': 'Contract',
    'dashboard.estimated': 'Estimated',
    'dashboard.paidAmount': 'Paid',
    'dashboard.rate': 'Rate',
    'dashboard.currentRate': 'Current rate',

    // Projects
    'projects.title': 'Project Management',
    'projects.subtitle': 'Manage your real estate properties',
    'projects.add': 'Add Project',
    'projects.cancel': 'Cancel',
    'projects.new': 'New Project',
    'projects.edit': 'Edit Project',
    'projects.name': 'Project Name',
    'projects.location': 'Location',
    'projects.status': 'Status',
    'projects.totalCost': 'Total Cost',
    'projects.paidAmount': 'Amount Paid',
    'projects.reservationDate': 'Reservation Date',
    'projects.expectedROI': 'Expected ROI',
    'projects.currency': 'Currency',
    'projects.paymentScheduleType': 'Payment Type',
    'projects.reservationDeposit': 'Reservation Deposit',
    'projects.save': 'Save',
    'projects.delete': 'Delete',
    'projects.confirmDelete': 'Are you sure you want to delete this project',
    'projects.noProjects': 'No Projects',
    'projects.addFirst': 'Start by adding your first project',
    'projects.duration': 'Duration',
    'projects.cannotAddManually': 'Cannot add new properties manually. Use the Evaluator tab to create a scenario.',
    'projects.convertedFromScenarios': 'Projects converted from approved scenarios',
    'projects.updateError': 'Error updating: ',

    // Administration
    'admin.title': 'Administration',
    'admin.investors': 'Investors',
    'admin.transactions': 'Transactions',
    'admin.currentAccount': 'Current Account 2025',
    'admin.capex': 'CAPEX 2025',
    'admin.rd': 'R&D / Dividends',

    // Investors
    'investors.title': 'Investor Management',
    'investors.subtitle': 'Manage investors and their documents',
    'investors.add': 'Add Investor',
    'investors.new': 'New Investor',
    'investors.edit': 'Edit Investor',
    'investors.firstName': 'First Name',
    'investors.lastName': 'Last Name',
    'investors.email': 'Email',
    'investors.phone': 'Phone',
    'investors.username': 'Username',
    'investors.shareClass': 'Share Class',
    'investors.totalShares': 'Total Shares',
    'investors.shareValue': 'Share Value',
    'investors.totalInvested': 'Total Invested',
    'investors.percentOwnership': '% Ownership',
    'investors.investmentType': 'Investment Type',
    'investors.joinDate': 'Join Date',
    'investors.accessLevel': 'Access Level',
    'investors.permissions': 'Permissions',
    'investors.documents': 'Documents',
    'investors.currentValue': 'Current Value',
    'investors.shares': 'Shares',
    'investors.ownership': 'Ownership',
    'investors.memberSince': 'Member since',
    'investors.noInvestors': 'No Investors',
    'investors.addFirstInvestor': 'Start by adding your first investor',

    // Transactions
    'transactions.title': 'Transactions',
    'transactions.new': 'New Transaction',
    'transactions.edit': 'Edit Transaction',
    'transactions.date': 'Date',
    'transactions.type': 'Type',
    'transactions.amount': 'Amount',
    'transactions.description': 'Description',
    'transactions.category': 'Category',
    'transactions.paymentMethod': 'Payment Method',
    'transactions.referenceNumber': 'Reference Number',
    'transactions.status': 'Status',
    'transactions.investor': 'Investor',
    'transactions.property': 'Property',
    'transactions.none': 'None',
    'transactions.noTransactions': 'No Transactions',
    'transactions.addFirst': 'Start by adding your first transaction',
    'transactions.totalIn': 'Inflows',
    'transactions.totalOut': 'Outflows',
    'transactions.balance': 'Balance',
    'transactions.filter': 'Filter',
    'transactions.allTypes': 'All Types',
    'transactions.allCategories': 'All Categories',
    'transactions.noMatch': 'No transactions match the selected filters',

    // Transaction Types
    'transactionType.investment': 'Investment',
    'transactionType.payment': 'Payment',
    'transactionType.dividend': 'Dividend',
    'transactionType.expense': 'Expense',

    // Categories
    'category.capital': 'Capital',
    'category.operation': 'Operation',
    'category.maintenance': 'Maintenance',
    'category.admin': 'Administration',

    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.suspended': 'Suspended',
    'status.complete': 'Complete',
    'status.pending': 'Pending',
    'status.cancelled': 'Cancelled',
    'status.reservation': 'Reservation',
    'status.construction': 'Construction',
    'status.completed': 'Completed',
    'status.rented': 'Rented',

    // Payment Methods
    'paymentMethod.transfer': 'Transfer',
    'paymentMethod.check': 'Check',
    'paymentMethod.cash': 'Cash',
    'paymentMethod.card': 'Card',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.actions': 'Actions',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.viewDetails': 'View Details',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.years': 'years',

    // Documents
    'documents.title': 'Documents',
    'documents.upload': 'Click to upload a document',
    'documents.uploading': 'Uploading...',
    'documents.noDocuments': 'No documents for this investor',
    'documents.deleteConfirm': 'Are you sure you want to delete this document?',

    // Current Account
    'currentAccount.title': 'Current Account',
    'currentAccount.subtitle': 'Aggregated view of transactions by category',
    'currentAccount.totalRevenues': 'Total Revenues',
    'currentAccount.operationalCosts': 'Operational Costs',
    'currentAccount.projectExpenses': 'Project Expenses',
    'currentAccount.netIncome': 'Net Income',
    'currentAccount.revenueDetails': 'Revenue Details',
    'currentAccount.operationDetails': 'Operation Cost Details',
    'currentAccount.projectDetails': 'Project Expense Details',
    'currentAccount.rentalIncome': 'Rental income',
    'currentAccount.otherIncome': 'Other income',
    'currentAccount.managementFees': 'Management fees',
    'currentAccount.utilities': 'Utilities',
    'currentAccount.insurance': 'Insurance',
    'currentAccount.maintenance': 'Maintenance',
    'currentAccount.propertyTaxes': 'Property taxes',
    'currentAccount.renovations': 'Renovations',
    'currentAccount.furnishing': 'Furnishing',
    'currentAccount.otherProjects': 'Other projects',
    'currentAccount.byProject': 'Details by Project',
    'currentAccount.noData': 'No Data',
    'currentAccount.noTransactionsFor': 'No transactions for',

    // Months
    'month.january': 'January',
    'month.february': 'February',
    'month.march': 'March',
    'month.april': 'April',
    'month.may': 'May',
    'month.june': 'June',
    'month.july': 'July',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'October',
    'month.november': 'November',
    'month.december': 'December',

    // Investment Types
    'investmentType.capital': 'Capital',
    'investmentType.debt': 'Debt',
    'investmentType.mixed': 'Mixed',

    // Access Levels
    'accessLevel.investor': 'Investor',
    'accessLevel.admin': 'Administrator',

    // Errors & Messages
    'error.generic': 'An error occurred',
    'error.loadingFailed': 'Failed to load data',
    'error.saveFailed': 'Failed to save',
    'error.deleteFailed': 'Failed to delete',
    'success.saved': 'Successfully saved',
    'success.deleted': 'Successfully deleted',
    'success.uploaded': 'Successfully uploaded',

    // Tax Reports
    'taxReports.title': 'Tax Reports',
    'taxReports.subtitle': 'T1135 and T2209 for Canadian tax filing',
    'taxReports.foreignAssets': 'Foreign assets',
    'taxReports.foreignTaxCredits': 'Foreign tax credits',
    'taxReports.t1135Required': 'T1135 required: Your foreign assets exceed $100,000 CAD',
    'taxReports.totalForeignAssets': 'Total foreign assets',
    'taxReports.foreignIncome': 'Foreign income',
    'taxReports.foreignProperties': 'Foreign properties',
    'taxReports.foreignPropertiesDetail': 'Foreign properties detail',
    'taxReports.exportPDF': 'Export PDF',
    'taxReports.country': 'Country',
    'taxReports.originalCost': 'Original cost',
    'taxReports.costCAD': 'Cost (CAD)',
    'taxReports.noForeignAssets': 'No foreign assets for this year',
    'taxReports.totalForeignIncome': 'Total foreign income',
    'taxReports.totalForeignTaxPaid': 'Total foreign tax paid',
    'taxReports.totalTaxCredit': 'Total tax credit',
    'taxReports.byCountry': 'By country',
    'taxReports.taxPaid': 'Tax paid',
    'taxReports.taxCredit': 'Tax credit',
    'taxReports.noForeignTaxData': 'No foreign tax data for this year',

    // Transaction Attachments
    'attachments.title': 'Attachments',
    'attachments.close': 'Close',
    'attachments.uploading': 'Uploading...',
    'attachments.dragDrop': 'Drag files here or click to select',
    'attachments.supportedFormats': 'PDF, Images, Word, Excel (max 10 MB per file)',
    'attachments.loading': 'Loading...',
    'attachments.noAttachments': 'No attachments for this transaction',
    'attachments.createTransactionFirst': 'Please create the transaction first before adding attachments.',
    'attachments.downloadFile': 'Download',
    'attachments.deleteFile': 'Delete',
    'attachments.deleteConfirm': 'Are you sure you want to delete',
    'attachments.uploadSuccess': 'File(s) uploaded successfully!',
    'attachments.uploadError': 'Upload error',
    'attachments.deleteSuccess': 'File deleted successfully!',
    'attachments.deleteError': 'Delete error',
    'attachments.downloadError': 'Download error',

    // Scenarios / Evaluator
    'scenarios.title': 'Evaluation Scenarios',
    'scenarios.subtitle': 'Create, analyze and vote on investment opportunities',
    'scenarios.newScenario': 'New Scenario',
    'scenarios.noScenarios': 'No Scenarios',
    'scenarios.createFirst': 'Create your first evaluation scenario',
    'scenarios.name': 'Project Name',
    'scenarios.unitNumber': 'Unit Number (Condo or Apartment)',
    'scenarios.address': 'Address (optional)',
    'scenarios.country': 'Country',
    'scenarios.stateRegion': 'State/Region/Province',
    'scenarios.promoterName': 'Promoter Name',
    'scenarios.brokerName': 'Broker Name',
    'scenarios.brokerEmail': 'Broker Email',
    'scenarios.companyName': 'Company Name',
    'scenarios.purchasePrice': 'Purchase Price ($)',
    'scenarios.initialFees': 'Initial Fees ($)',
    'scenarios.transactionFeesType': 'Transaction Fees',
    'scenarios.amountValue': 'Amount',
    'scenarios.currency': 'Currency',
    'scenarios.rentAmount': 'Rent Amount',
    'scenarios.rentType': 'Rent Type',
    'scenarios.rentCurrency': 'Rent Currency',
    'scenarios.monthly': 'Monthly',
    'scenarios.nightly': 'Per Night',
    'scenarios.constructionStatus': 'Construction Status',
    'scenarios.constructionStatusLabel': 'Status',
    'scenarios.inProgress': 'Under Construction',
    'scenarios.completed': 'Construction Completed',
    'scenarios.deliveryDate': 'Delivery Date',
    'scenarios.completionYear': 'Completion Year',
    'scenarios.monthlyRent': 'Monthly Rent ($)',
    'scenarios.annualAppreciation': 'Annual Appreciation (%)',
    'scenarios.occupancyRate': 'Occupancy Rate (%)',
    'scenarios.managementFees': 'Management Fees (%)',
    'scenarios.projectDuration': 'Project Duration (years)',
    'scenarios.taxRate': 'Tax Rate on Rental Income (%)',
    'scenarios.annualRentIncrease': 'Annual Rent Increase (%)',
    'scenarios.rentalIncomeAnalysis': 'Rental Income Analysis',
    'scenarios.numberOfNights': 'Number of Nights',
    'scenarios.accommodationPrice': 'Accommodation Price',
    'scenarios.annualIncome': 'Annual Income',
    'scenarios.annualRevenue': 'Annual Revenue',
    'scenarios.tax': 'Tax',
    'scenarios.netIncome': 'Net Income',
    'scenarios.netIncomeComparison': 'Net Income Comparison',
    'scenarios.roiTimeline': 'ROI Timeline with Rent Increases',
    'scenarios.nightlyRate': 'Nightly Rate',
    'scenarios.cumulativeIncome': 'Cumulative Income',
    'scenarios.roiProgress': 'ROI Progress',
    'scenarios.paymentTerms': 'Payment Terms',
    'scenarios.addTerm': 'Add Term',
    'scenarios.noPaymentTerms': 'No payment terms defined',
    'scenarios.termLabel': 'Label',
    'scenarios.termLabelPlaceholder': 'Ex: Initial deposit',
    'scenarios.amountType': 'Amount Type',
    'scenarios.percentage': 'Percentage (%)',
    'scenarios.fixedAmount': 'Fixed Amount',
    'scenarios.percentageValue': 'Percentage (%)',
    'scenarios.amountUSD': 'Amount (USD)',
    'scenarios.dueDate': 'Due Date',
    'scenarios.calculatedAmount': 'Calculated Amount',
    'scenarios.basicInfo': 'Basic Information',
    'scenarios.promoterData': 'Promoter Data',
    'scenarios.promoterDocuments': 'Promoter Documents',
    'scenarios.analyze': 'Analyze',
    'scenarios.analyzing': 'Analyzing...',
    'scenarios.submitForVote': 'Submit for Vote',
    'scenarios.forceApproval': 'Force Approval (Admin)',
    'scenarios.markAsPurchased': 'Mark as Purchased',
    'scenarios.exportPDF': 'Export PDF',
    'scenarios.back': 'Back',
    'scenarios.create': 'Create Scenario',
    'scenarios.view': 'View',
    'scenarios.required': 'required',
    'scenarios.optional': 'optional',
    'scenarios.toBeDefinedLocation': 'To be defined',

    // Scenario Status
    'scenarioStatus.draft': 'Draft',
    'scenarioStatus.pending_vote': 'Pending Vote',
    'scenarioStatus.approved': 'Approved',
    'scenarioStatus.rejected': 'Rejected',
    'scenarioStatus.purchased': 'Purchased',

    // Scenario Types
    'scenarioType.conservative': 'Conservative',
    'scenarioType.moderate': 'Moderate',
    'scenarioType.optimistic': 'Optimistic',

    // Scenario Results
    'scenarioResults.avgAnnualReturn': 'Avg Annual Return',
    'scenarioResults.totalReturn': 'Total Return',
    'scenarioResults.finalValue': 'Final Value',
    'scenarioResults.breakEven': 'Break Even',
    'scenarioResults.year': 'Year',
    'scenarioResults.evaluation': 'Evaluation',
    'scenarioResults.projection': 'Annual Projection',
    'scenarioResults.propertyValue': 'Property Value',
    'scenarioResults.revenues': 'Revenues',
    'scenarioResults.fees': 'Fees',
    'scenarioResults.net': 'Net',
    'scenarioResults.cashflow': 'Cashflow',
    'scenarioResults.recommendation': 'Recommendation',
    'scenarioResults.recommended': 'recommended',
    'scenarioResults.notRecommended': 'not recommended',
    'scenarioResults.toConsider': 'to consider with caution',
    'scenarioResults.scenarioLabel': 'Scenario',
    'scenarioResults.project': 'Project',
    'scenarioResults.over': 'over',
    'scenarioResults.attractiveReturn': 'Attractive return',
    'scenarioResults.lowReturn': 'Low return',
    'scenarioResults.moderateReturn': 'Moderate return',
    'scenarioResults.quickBreakEven': 'Quick break even',
    'scenarioResults.distantBreakEven': 'Distant break even',
    'scenarioResults.acceptableBreakEven': 'Acceptable break even',

    // Voting
    'voting.status': 'Vote Status',
    'voting.votes': 'votes',
    'voting.votesReceived': 'Votes Received',
    'voting.approvals': 'Approvals',
    'voting.rejections': 'Rejections',
    'voting.approvalRate': 'Approval Rate',
    'voting.yourVote': 'Your Vote',
    'voting.approve': 'Approve',
    'voting.reject': 'Reject',
    'voting.voteRecorded': 'Vote recorded!',
    'voting.voteError': 'Error recording vote',
    'voting.individualVotes': 'Individual Votes',
    'voting.noVotingPermission': 'You don\'t have permission to vote on this scenario',
    'voting.onlyAdminsCanForce': 'Only administrators can force approval',
    'voting.forceConfirm': 'Are you sure you want to FORCE approval of this scenario?\n\nThis bypasses the normal voting system and marks the scenario as approved by investors.',
    'voting.forcedSuccess': 'Scenario marked as approved (forced by admin)',
    'voting.forceError': 'Error forcing approval',
    'voting.totalEligibleVoters': 'Eligible Voters',

    // Documents
    'scenarioDocuments.title': 'Promoter Documents',
    'scenarioDocuments.upload': 'Add',
    'scenarioDocuments.uploading': 'Uploading...',
    'scenarioDocuments.noDocuments': 'No documents',
    'scenarioDocuments.view': 'View',
    'scenarioDocuments.delete': 'Delete',
    'scenarioDocuments.uploadSuccess': 'Document uploaded successfully!',
    'scenarioDocuments.uploadError': 'Error uploading document',
    'scenarioDocuments.deleteConfirm': 'Are you sure you want to delete this document?',
    'scenarioDocuments.deleteSuccess': 'Document deleted',
    'scenarioDocuments.deleteError': 'Error deleting document',
    'scenarioDocuments.fileTooLarge': 'File is too large (max 50MB)',

    // Scenario Conversion
    'scenarioConvert.mustBeApproved': 'The scenario must be approved before marking as purchased',
    'scenarioConvert.confirmConversion': 'Do you want to convert this scenario to an active project?',
    'scenarioConvert.success': 'Scenario successfully converted to active project!',
    'scenarioConvert.error': 'Error converting to project',
    'scenarioConvert.analyzeFirst': 'Please analyze the scenario before submitting for vote',
    'scenarioConvert.votingInfo': 'Submitted for investor voting',
    'scenarioConvert.approvedInfo': 'Approved - Ready to be purchased',
    'scenarioConvert.purchasedInfo': 'Converted to active project',

    // Project Scenario Info
    'projectScenario.title': 'Evaluation Scenario',
    'projectScenario.createdOn': 'Created on',
    'projectScenario.from': 'From scenario',

    // Admin - Investor Voting Rights
    'investors.votingRights': 'Voting Rights',
    'investors.canVote': 'Can vote on scenarios',

    // Messages
    'scenarios.fillRequired': 'Please fill in all required fields',
    'scenarios.created': 'Scenario created successfully!',
    'scenarios.createError': 'Error creating scenario',
    'scenarios.analyzed': 'Analysis complete! 3 scenarios have been generated.',
    'scenarios.analyzeError': 'Error analyzing scenario',
    'scenarios.submitted': 'Scenario submitted for investor voting!',
    'scenarios.submitError': 'Error submitting for vote',
    'scenarios.noAddProjects': 'Cannot add new properties manually. Use the Evaluator tab to create a scenario.',

    // Project List Messages
    'projects.convertedFrom': 'Projects converted from approved scenarios',
    'projects.noActiveProjects': 'No Active Projects',
    'projects.createdViaEvaluator': 'Projects are automatically created from',
    'projects.workflow': 'Create scenario → Analyze → Investor vote → Mark as purchased',

    // User Guide
    'userGuide.title': 'User Manual',
    'userGuide.subtitle': 'Complete guide to using the CERDIA platform',
    'userGuide.searchPlaceholder': 'Search in the guide...',
    'userGuide.noResults': 'No results found for',
    'userGuide.dashboard': 'Dashboard',
    'userGuide.projectManagement': 'Project Management',
    'userGuide.evaluator': 'Evaluator / Scenarios',
    'userGuide.reservations': 'Reservations Calendar',
    'userGuide.administration': 'Administration',
    'userGuide.treasury': 'Treasury',
    'userGuide.projectManagementAdmin': 'Project Management (Admin)',
    'userGuide.budgeting': 'Budgeting',
    'userGuide.userManual': 'User Manual',
    'userGuide.notepad': 'Notepad',

    // User Guide - Dashboard
    'userGuide.dashboardOverview': 'Overview',
    'userGuide.dashboardOverviewDesc': 'The dashboard displays a summary of your investments in real time.',
    'userGuide.dashboardStep1': 'Total Investors: Sum of contributions in CAD',
    'userGuide.dashboardStep2': 'Real Estate Investment: Amount invested in USD converted to CAD',
    'userGuide.dashboardStep3': 'Operating Expenses: CAPEX + R&D',
    'userGuide.dashboardStep4': 'Current Account: Available funds calculated automatically',
    'userGuide.exchangeRate': 'Exchange Rate',
    'userGuide.exchangeRateDesc': 'The widget displays the USD→CAD rate updated daily from the Bank of Canada.',
    'userGuide.properties': 'Properties',
    'userGuide.propertiesDesc': 'List of your properties with payment progress and expected ROI.',

    // User Guide - Project Management
    'userGuide.projectOverview': 'Overview',
    'userGuide.projectOverviewDesc': 'Manage your real estate projects with deadline and milestone tracking.',
    'userGuide.createProject': 'Create a project',
    'userGuide.createProjectDesc': 'Create a new project by clicking "New Project".',
    'userGuide.createProjectStep1': 'Enter the project name',
    'userGuide.createProjectStep2': 'Set start and end dates',
    'userGuide.createProjectStep3': 'Add a description',
    'userGuide.createProjectStep4': 'Select initial status',
    'userGuide.milestones': 'Milestones',
    'userGuide.milestonesDesc': 'Define project key stages with dates and deliverables.',
    'userGuide.risks': 'Risks',
    'userGuide.risksDesc': 'Identify and manage potential project risks.',
    'userGuide.contractors': 'Contractors',
    'userGuide.contractorsDesc': 'Manage contacts and contracts of involved contractors.',

    // User Guide - Evaluator
    'userGuide.scenarioCreation': 'Scenario Creation',
    'userGuide.scenarioCreationDesc': 'Create investment scenarios to evaluate profitability.',
    'userGuide.scenarioStep1': 'Click "New Scenario"',
    'userGuide.scenarioStep2': 'Enter property information',
    'userGuide.scenarioStep3': 'Define purchase price and fees',
    'userGuide.scenarioStep4': 'Configure promoter data (rent, charges, etc.)',
    'userGuide.scenarioStep5': 'Add payment terms',
    'userGuide.scenarioTypes': 'Scenario Types',
    'userGuide.scenarioTypesDesc': 'Three types available: Conservative, Moderate, Optimistic with different financial projections.',
    'userGuide.documents': 'Documents',
    'userGuide.documentsDesc': 'Upload and manage scenario-related documents (contracts, plans, etc.).',
    'userGuide.vote': 'Vote',
    'userGuide.voteDesc': 'Submit the scenario for investor voting for validation.',
    'userGuide.reservationsAfterPurchase': 'Reservations (after purchase)',
    'userGuide.reservationsAfterPurchaseDesc': 'Manage booking calendar and rental income once property is purchased.',

    // User Guide - Reservations
    'userGuide.calendarView': 'Calendar View',
    'userGuide.calendarViewDesc': 'View all reservations for your rented properties.',
    'userGuide.createReservation': 'Create a reservation',
    'userGuide.createReservationDesc': 'Add a new reservation by selecting dates and property.',
    'userGuide.management': 'Management',
    'userGuide.managementDesc': 'Edit or cancel existing reservations.',

    // User Guide - Administration
    'userGuide.investors': 'Investors',
    'userGuide.investorsDesc': 'Manage investors, their shares and permissions.',
    'userGuide.investorsStep1': 'Add an investor: Enter name, email, shares',
    'userGuide.investorsStep2': 'Edit: Click the pencil icon',
    'userGuide.investorsStep3': 'Delete: Trash icon (with confirmation)',
    'userGuide.transactions': 'Transactions',
    'userGuide.transactionsDesc': 'Record all financial transactions.',
    'userGuide.transactionsStep1': 'Types: Investment, Payment, Dividend, Other',
    'userGuide.transactionsStep2': 'Attach supporting documents (invoices, receipts)',
    'userGuide.transactionsStep3': 'Link to investors and properties',
    'userGuide.capex': 'CAPEX',
    'userGuide.capexDesc': 'Manage capital expenditures (investment and operation).',
    'userGuide.rdDividends': 'R&D / Dividends',
    'userGuide.rdDividendsDesc': 'Track R&D expenses and dividend distributions.',
    'userGuide.taxReports': 'Tax Reports',
    'userGuide.taxReportsDesc': 'Generate tax reports for authorities.',
    'userGuide.roiPerformance': 'ROI Performance',
    'userGuide.roiPerformanceDesc': 'Analyze return on investment by property and globally.',
    'userGuide.syncRevenue': 'Sync Revenue',
    'userGuide.syncRevenueDesc': 'Synchronize revenue from booking platforms (Booking.com, Airbnb).',

    // User Guide - Treasury
    'userGuide.treasuryOverview': 'Overview',
    'userGuide.treasuryOverviewDesc': 'Financial dashboard with current balance, monthly inflows/outflows.',
    'userGuide.cashFlowForecasts': 'Cash Flow Forecasts',
    'userGuide.cashFlowForecastsDesc': 'View forecast cash flows over 12 months.',
    'userGuide.bankReconciliation': 'Bank Reconciliation',
    'userGuide.bankReconciliationDesc': 'Reconcile your transactions with your bank statements.',
    'userGuide.paymentSchedule': 'Payment Schedule',
    'userGuide.paymentScheduleDesc': 'Manage scheduled payments with due date alerts.',
    'userGuide.alerts': 'Alerts',
    'userGuide.alertsDesc': 'Configure alerts for low balance, late payments, etc.',

    // User Guide - Project Management Admin
    'userGuide.adminAccess': 'Administrator Access',
    'userGuide.adminAccessDesc': 'Administrative version with advanced project management features.',
    'userGuide.timeline': 'Timeline',
    'userGuide.timelineDesc': 'Chronological view of projects with dependencies.',
    'userGuide.resources': 'Resources',
    'userGuide.resourcesDesc': 'Resource allocation (budget, personnel, equipment).',

    // User Guide - Budgeting
    'userGuide.budgetCreation': 'Budget Creation',
    'userGuide.budgetCreationDesc': 'Create annual budgets by category.',
    'userGuide.budgetStep1': 'Select fiscal year',
    'userGuide.budgetStep2': 'Add budget lines (name, category, amount)',
    'userGuide.budgetStep3': 'Define periods (monthly, quarterly, annual)',
    'userGuide.budgetStep4': 'Configure alert thresholds',
    'userGuide.consumptionTracking': 'Consumption Tracking',
    'userGuide.consumptionTrackingDesc': 'View % of budget consumed with visual indicators (green/orange/red).',
    'userGuide.varianceAnalysis': 'Variance Analysis',
    'userGuide.varianceAnalysisDesc': 'Compare planned vs actual to identify overruns.',
    'userGuide.approval': 'Approval',
    'userGuide.approvalDesc': 'Approval workflow for budget modifications.',

    // User Guide - Notepad
    'userGuide.interactiveGuide': 'Interactive Guide',
    'userGuide.interactiveGuideDesc': 'This guide you are currently viewing!',
    'userGuide.todoLists': 'To-Do Lists',
    'userGuide.todoListsDesc': 'Create and manage your personal task lists.',
    'userGuide.todoStep1': 'Create a new list',
    'userGuide.todoStep2': 'Add tasks',
    'userGuide.todoStep3': 'Check off completed tasks',
    'userGuide.todoStep4': 'Delete obsolete tasks',
    'userGuide.notes': 'Notes',
    'userGuide.notesDesc': 'Take free notes related to your projects.',

    // Notes Manager
    'notes.title': 'Notepad',
    'notes.todoLists': 'To-Do Lists',
    'notes.notes': 'Notes',
    'notes.newList': 'New List',
    'notes.newNote': 'New Note',
    'notes.listName': 'List Name',
    'notes.listNamePlaceholder': 'My to-do list',
    'notes.createList': 'Create',
    'notes.cancel': 'Cancel',
    'notes.addTask': 'Add a task',
    'notes.taskPlaceholder': 'What needs to be done?',
    'notes.add': 'Add',
    'notes.deleteList': 'Delete list',
    'notes.confirmDeleteList': 'Are you sure you want to delete this list and all its tasks?',
    'notes.noLists': 'No to-do list',
    'notes.createFirstList': 'Create your first to-do list to get organized',
    'notes.tasksCompleted': 'tasks completed',
    'notes.noteTitle': 'Note Title',
    'notes.noteTitlePlaceholder': 'My note',
    'notes.noteContent': 'Content',
    'notes.noteContentPlaceholder': 'Write your note here...',
    'notes.save': 'Save',
    'notes.delete': 'Delete',
    'notes.confirmDeleteNote': 'Are you sure you want to delete this note?',
    'notes.noNotes': 'No notes',
    'notes.createFirstNote': 'Create your first note to store your ideas',
    'notes.createdOn': 'Created on',
    'notes.updatedOn': 'Updated on',
    'notes.edit': 'Edit',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr')

  // Load language preference from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
