// 📦 PERFORMANCE: Import optimisé des icônes (tree-shaking)
// Au lieu de: import { Home, User, ... } from 'lucide-react' (importe TOUT)
// On fait: import { Home } from 'lucide-react/dist/esm/icons/home' (importe SEULEMENT Home)

// Ce fichier centralise tous les imports d'icônes pour:
// 1. Réduire le bundle size (seulement icônes utilisées)
// 2. Faciliter la maintenance (un seul endroit)
// 3. Améliorer tree-shaking

export {
  Home,
  User,
  Users,
  Building,
  FileText,
  DollarSign,
  TrendingUp,
  TrendingDown,
  PieChart,
  BarChart3,
  Settings,
  LogOut,
  Plus,
  Minus,
  X,
  Check,
  AlertTriangle,
  Info,
  Edit,
  Trash2,
  Download,
  Upload,
  Search,
  Filter,
  Calendar,
  Clock,
  Mail,
  Phone,
  MapPin,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  AlertCircle,
  CheckCircle,
  XCircle,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Menu,
  MoreVertical,
  MoreHorizontal,
  RefreshCw,
  Save,
  Copy,
  ExternalLink,
  Link,
  Unlink,
  Image,
  Folder,
  File,
  Archive,
  Package,
  ShoppingCart,
  CreditCard,
  Wallet,
  Calculator,
  Percent,
  Hash,
  Star,
  Heart,
  Bookmark,
  Share2,
  Send,
  Printer,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  Undo,
  Redo,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  LogIn,
} from 'lucide-react'
